### PR TITLE
Samples code cleanup and verification that all samples run

### LINKED ISSUE #2935: Validate that all samples run
There are multiple runtime exceptions I'm experiencing.

An example is the Saving example [here](https://github.com/dotnet/EntityFramework.Docs/blob/2667d7425ab1043f5599c182c75b9112389b46c3/samples/core/Saving/Basics/Sample.cs#L62):

`Queries performing 'Last' operation must have a deterministic sort order. Rewrite the query to apply an 'OrderBy' clause on the sequence before calling 'Last'.'`

I noticed that the the github actions [yml](https://github.com/dotnet/EntityFramework.Docs/blob/2667d7425ab1043f5599c182c75b9112389b46c3/.github/workflows/build-samples.yml#L35) doesn't run the samples, so which makes it difficult to determine if the problem is in my environment or not.

Are there plans to add `dotnet run` to CI/CD and if not would you take a PR for that?

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #2935

### CODE REVIEW

File: samples/core/CompiledQueries/Program.cs [hunk 1]
```diff
@@ -10,6 +10,21 @@ public class Program
     {
         private static void Main()
         {
+            using (var db = new AdventureWorksContext())
```
Comment (roji) [inline samples/core/CompiledQueries/Program.cs:13]: We should convert this to a proper BDN benchmark, added a note in #502.

**Review by roji — APPROVED** [review]
Should also bring in the EF Core .editorconfig

**Comment by ajcvickers** [comment]
Added editor.config. (Good catch; this results in fewer changes in indentation.)
